VERBOSE: True

MODEL:
  SESSION: 'LensNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 4 
  NUM_EPOCHS: 200 
  LR_INITIAL: 2e-4 
  LR_MIN: 1e-6
  SEED: 3407 
  WANDB: False

TRAINING:
  VAL_AFTER_EVERY: 1 
  RESUME: False
  PS_W: 320 
  PS_H: 320 
  TRAIN_FILE: '../BaiduNetdiskDownload/dataset/MWDNs_train.npz' 
  VAL_FILE: '../BaiduNetdiskDownload/dataset/lensless/MWDNs_test.npz'    
  SAVE_DIR: './checkpoints/'     
  ORI: False 

TESTING:
  WEIGHT: './checkpoints/LensNet-MWDNs.pth'
  SAVE_IMAGES: True 